apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: default
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.5.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  # ✅ Auto-create namespace if missing
    automated:
      prune: true
      selfHeal: true